[Jimmy]moda - detail component
zbqmgldjfh/sidedish pull request #32
Opened 2022-04-28 02:09 UTC by dlwnstjrzz

issue #24 

Modal디렉토리에서 RelatedProduct가 캐러셀입니다
캐러셀을 import해서 쓰려고했는데 조금씩 달라지는 부분이 있어서 modal용으로 파일(ModalCarouselProvider)을 하나 더 만들었고 useCarousel은 공용으로 써도 일단 문제는 없었습니다

modal에서 쓰는 데이터가 foods.js 데이터에는 없어서 임시로 modalFoods라는 mock데이터를 만들었습니다 
이부분은 백엔드 api 적용하면서 좀 바뀔거같네요 

가끔 눌러도 모달이 안나오는 음식들이 있는데 로직문제가 아니라 목데이터에 추가를 안해놔서 그렇습니다

2022-04-28 02:33 UTC, healtheloper requested changes
Modal 안에 Modal 과 관련된 여러가지 Component 들이 보이는데요,
Modal 은 정말 Modal 의 역할만 한다고 가정하면
Modal 안에 있는 Component 들은 어떻게 옮겨서 사용해야 할까요?

Modal 안에 Main Page Component 를 쓰고싶다면? 
Modal 안에 Login Page Component 를 쓰고싶다면? 

재사용성에 대해서 고민한 이후 Component 를 재사용성있게 어떻게 짜야할 지 고민해보면 좋을 것 같습니다.

2022-04-28 02:33 UTC, healtheloper commented on FE/src/components/Modal/OrderButton.js
> +
제가 Button 관련 Components 를 만들었는 데 사라졌네요?! 
그게 hover 랑 disabled 관련 CSS 적용 시켜놓았는데, 이전 Commit 로그로 찾아서 적용시켜도 좋을 것 같습니다~

2022-04-28 02:33 UTC, healtheloper commented on FE/src/components/Modal/OrderButton.js
> +  background-color: ${colors.black};
440, 58, 472, 490
매직넘버 너무 많은데, 따로 파일을 둬서 관리할 순 없을까요?

2022-04-28 02:33 UTC, healtheloper commented on FE/src/components/Modal/ModalFoodCard.js
> +const ModalFoodCard = ({ food }) => (
기존 FoodCard 와 무슨 차이가 있을까요?
FoodCard 를 재사용한다면, 그 차이는 어떻게 관리할 수 있을까요?

2022-04-28 02:33 UTC, healtheloper commented on FE/src/components/Modal/ModalFoodCards.js
> +  <CardsWrap size={size}>
FoodCard 와 비슷한 맥락으로 재사용 가능하지 않을까 란 생각이 드네요~!

2022-04-28 02:33 UTC, healtheloper commented on FE/src/context/ModalCardInfoContext.js
> +  const [thumbImg, setThumbImg] = useState([]);
배열을 사용한다면 복수의 표현을 해주는것도 좋죠

2022-04-28 02:33 UTC, healtheloper commented on FE/src/mocks/foods.js
> +    s_price: '12640',
데이터 구조가 이렇게 바뀐 이유가 무엇일까요?

2022-04-28 02:33 UTC, healtheloper commented on FE/src/constants/fonts.js
> +  },
fonts 를 통해 관리하니 확장성이 좋아지네요 👍

2022-04-28 02:33 UTC, healtheloper commented on FE/src/components/Modal/TotalCost.js
> +        {(ModalInfo.cardInfo.s_price * ModalInfo.amount).toLocaleString()}원
wonToMoney 와 같은 utils 를 만들어보는게 어떨까요?
12,000원 -> 12000

사실 제가 moneyToWon 은 만들어서 쓰고있는 중인데, (백엔드에서 온 데이터가 9000 이래서) wonToMoney 는 지미가 만들어 보셔도 좋을 것 같습니다.
화면에 보여지는 것은 moneyToWon 적용시키지 않고 보여주는 것으로 해도 좋을 것 같아요 제가 만든걸로 쓰면 되니까요~!

2022-04-28 02:33 UTC, healtheloper commented on FE/src/components/Modal/ProductImg.js
> +    ModalInfo.thumbImg.splice(thumbImgInfo.idx, 1, ModalInfo.topImg);
제생각에 thumbImg 를 splice 한다는 것은 원본 배열을 바꾸는 것인데,
부수효과가 일어나므로 함수형 프로그래밍과는 거리가 멀어보입니다.

2022-04-28 02:33 UTC, healtheloper commented on FE/src/components/Carousel/ModalCarouselProvider.js
> +const ModalCarouselProvider = ({
CarouselProvider 를 재사용하려면 어떻게할 수 있을까요?

2022-04-28 02:49 UTC, dlwnstjrzz commented on FE/src/mocks/foods.js
> +    s_price: '12640',
바꾼 이유가 모달창에서 음식주문 수량을 바꿨을 때 가격도 같이 바뀌게 하려면 타입이 숫자여야해서 바꿨습니다
아래 리뷰 주신것처럼 wonToMoney util을 만들까 생각도 했었는데 백엔드에서 숫자로 주시지 않나요?? moneyToWon만 있어도 될거같아서 일단은 이렇게 해놨습니다

2022-04-28 02:51 UTC, dlwnstjrzz commented on FE/src/components/Modal/ProductImg.js
> +    ModalInfo.thumbImg.splice(thumbImgInfo.idx, 1, ModalInfo.topImg);
어제는 splice만 생각이 났는데 slice를 쓰면 원본배열을 바꾸지 않아도 될거같네요 다시 한 번 해보겠습니다~

2022-04-28 03:03 UTC, healtheloper commented on FE/src/mocks/foods.js
> +    s_price: '12640',
만약 어딘가에서 해당 값을 가져올 때 `~~원` 형태로 가져올 수도 있지 않을까~~ 해서 만들어보면 좋겠다 말씀을 드렸는데
생각해보니 state 를 숫자로만 관리하면 될 것같아서 moneyToWon 만 있으면 될 듯 하네요 ㅎㅎ

2022-04-28 03:44 UTC, dlwnstjrzz commented on FE/src/components/Modal/ModalFoodCards.js
> +  <CardsWrap size={size}>
foodcard와 foodCards 모두 type을 props로 받아줘서 재사용할 수 있게 바꿨습니다~

2022-04-28 09:49 UTC, healtheloper requested changes
리뷰 추가로 드렸습니다~~
이전에 리뷰 드렸던게 이번 change 를 봤을 때 적용이 안된것도 있는 것 같아요
고생하셨습니다 지미~~

2022-04-28 09:49 UTC, healtheloper commented on FE/src/App.js
> +        <Modal ModalDetail={<FoodModal />} />
👍
FoodModal 은 children 으로도 줄 수 있어 보입니다.
props 의 컨벤션은 카멜케이스로 보통 쓰인다고 하더라구요, (modalDetail)

2022-04-28 09:49 UTC, healtheloper commented on FE/src/components/Main/FoodCard.js
>        ModalInfo.setModalDisplay('block');
저도 잘 몰라서 그러는데, ModalInfo 내부에서 modalDisplay 에 따른 핸들러를 만들어서 쓸 수있나요?
```js
// FoodCard.js
const images = { main:food.image, thumbs: [...]}
const foodData = { ...food, ...modalFoods[food.detail.hash]}
changeFoodModalInfo({foodData, images});

// ModalCardInfoContext.js
const changeFoodModalInfo = ({foodData, images}) => {
  ModalInfo.setCardInfo({...})
  ModalInfo.setThumbImg(...);
  ....
}
```

2022-04-28 09:49 UTC, healtheloper commented on FE/src/components/Main/FoodCard.js
> +      <CardDescription type={type}>
type 을 넘겨주기보다, descDisplay 를 넘겨주는게 맞지않을까 생각이 듭니다.
type 을 넘겨주면 styled component 안에서 연산을 통해 스타일을 지정하는데 그게 styled 의 역할인지 고민되더라구요.
또 로직이 너무 길어지면 return 위에서 따로 변수를 선언해서 넣어줘도 좋구요

2022-04-28 09:49 UTC, healtheloper commented on FE/src/components/Main/FoodCard.js
> +      <BadgeWrap type={type}>
위와 동일하게 생각!

2022-04-28 09:49 UTC, healtheloper commented on FE/src/components/Main/FoodCards.js
> +      : 'padding: 80px;'}
템플릿 리터럴을 쓸 때에는 indent 신경을 잘 써줘야하는 것 같아요

2022-04-28 09:49 UTC, healtheloper commented on FE/src/components/Main/FoodCards.js
> +  <CardsWrap size={size} type={type}>
type -> 위와 동일
isModal 정도?

2022-04-28 09:49 UTC, healtheloper commented on FE/src/components/Modal/FoodModal.js
> +  background-color: white;
colors.white

2022-04-28 09:49 UTC, healtheloper commented on FE/src/components/Modal/Modal.js
> +  height: 47.8rem;
반응형을 위해 rem 을 쓰긴 했는데, 이런 숫자가 매직넘버로 느껴져야 하는걸까요? 저도 잘 모르겠네요.

2022-04-28 09:49 UTC, healtheloper commented on FE/src/components/Modal/Modal.js
> +      <ModalWrap>{ModalDetail}</ModalWrap>
위에서 말씀 드렸듯 children 으로 받아서 jsx 로 쓰는게 좋을듯.

```jsx
<ModalWrap>
  <ModalDetail />
</ModalWrap>
```

2022-04-28 09:49 UTC, healtheloper commented on FE/src/components/Modal/OrderButton.js
> +const OrderButton = () => (
사라진 제 button 찾아주세요ㅕ..

2022-04-28 09:49 UTC, healtheloper commented on FE/src/components/Modal/ProductDetail.js
> +import TotalCost from './TotalCost';
이제 Detail 페이지를 Modal 폴더 안에서 관리하기보다
Main 처럼 components 에 폴더를 별도로 두어서 관리하는게 맞다고 생각합니다.

2022-04-28 09:49 UTC, healtheloper commented on FE/src/components/Modal/ProductDetail.js
> +  padding-left: 3%;
padding: 2% 0% 3% 3%;
로 할수있긴 해요,

2022-04-28 09:49 UTC, healtheloper commented on FE/src/components/Modal/ProductDetail.js
> +        <Close onClick={onCloseClick}>
CloseButton 이 더 명시적으로 보이는 듯 합니다.

2022-04-28 09:49 UTC, healtheloper commented on FE/src/components/Modal/ProductImg.js
> +    newThumbImg.splice(thumbImgInfo.idx, 1, ModalInfo.topImg);
여기도 splice

2022-04-28 09:49 UTC, healtheloper commented on FE/src/components/Modal/RelatedProduct.js
> +      right: 3.4em;
템플릿 리터럴을 사용할 때에는 indent 도 신경써서 해야할 것 같아요~!

2022-04-28 10:08 UTC, merged

2022-04-30 07:56 UTC, dlwnstjrzz commented on FE/src/components/Modal/Modal.js
> +      <ModalWrap>{ModalDetail}</ModalWrap>
children으로 받는다는게 상위 컴포넌트의 props로 하위 컴포넌트를 전달해준다는 뜻인가요?

파크가 적어주신 코드는
```javascript
<ModalWrap>
  <ModalDetail />
</ModalWrap>
```
modal 컴포넌트를 재사용할 수 없는 구조 아닌가요??

modal 컴포넌트를 재사용하고 그 안에 들어가는 컴포넌트는 매번 바뀌는 식이라서 props로 받아줘야한다고 생각했는데 아닌가요??

2022-05-01 15:05 UTC, healtheloper commented on FE/src/components/Modal/Modal.js
> +      <ModalWrap>{ModalDetail}</ModalWrap>
JSX 의 child 를 어떻게 넣을 수 있을지 간단하게 알려드린거고 실제로는 Modal 에 props 로 받은 것을 또 다시 넘겨줄 수도 있겠고, 아니면 ModalDetail 컴포넌트 내부에서 Context 를 활용할 수도 있을 것 같아요